lib/rentsy_web/router.ex
defmodule RentsyWeb.Router do
  use RentsyWeb, :router

  import RentsyWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RentsyWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", RentsyWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: RentsyWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", RentsyWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", RentsyWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", RentsyWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/rentsy_web/views/layout_view.ex
defmodule RentsyWeb.LayoutView do
  use RentsyWeb, :view

  def is_public_page?(conn = %Plug.Conn{path_info: path_info}) do
    path_info
    |> join_path()
    |> String.equivalent?(Routes.page_path(conn, :index))
  end

  def is_session_page?(conn = %Plug.Conn{path_info: path_info}) do
    current_page = path_info |> join_path()

    [
      Routes.user_session_path(conn, :new),
      Routes.user_registration_path(conn, :new),
      Routes.user_reset_password_path(conn, :new)
    ]
    |> Enum.any?(&String.equivalent?(current_page, &1))
  end

  def is_individual?(%Plug.Conn{assigns: %{current_user: %{type: "individual"}}}), do: true
  def is_individual?(%Plug.Conn{assigns: %{current_user: %{type: _}}}), do: false

  def is_landlord?(%Plug.Conn{assigns: %{current_user: %{type: "landlord"}}}), do: true
  def is_landlord?(%Plug.Conn{assigns: %{current_user: %{type: _}}}), do: false

  def get_user_label(%Plug.Conn{assigns: %{current_user: %{type: "individual"}}}),
    do: "Individual"

  def get_user_label(%Plug.Conn{assigns: %{current_user: %{type: "landlord"}}}),
    do: "Landlord"

  def get_full_name(%Plug.Conn{assigns: %{current_user: %{first_name: first, last_name: last}}}),
    do: first <> " " <> last

  defp join_path(path_info), do: "/" <> Enum.join(path_info, "/")
end

lib/rentsy_web/templates/layout/partials/_dropdown.html.eex
<div class="navbar-nav flex-row order-md-last">
    <div class="nav-item dropdown">
        <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-toggle="dropdown">
            <div class="d-none d-xl-block pl-2">
                <div><%= get_full_name(@conn) %></div>
                <div class="mt-1 small text-muted"><%= get_user_label(@conn) %></div>
            </div>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="<%= Routes.user_settings_path(@conn, :edit) %>">
                Settings
            </a>
            <div class="dropdown-divider"></div>
            <%= link "Logout", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "dropdown-item" %>
        </div>
    </div>
</div>

lib/rentsy_web/templates/layout/partials/_footer.html.eex
<footer class="footer footer-transparent">
    <div class="container">
    <div class="row text-center align-items-center flex-row-reverse">
        <div class="col-lg-auto ml-lg-auto">
        <ul class="list-inline list-inline-dots mb-0">
            <li class="list-inline-item"><a href="./docs/index.html" class="link-secondary">About Us</a></li>
            <li class="list-inline-item"><a href="./faq.html" class="link-secondary">Contact Us</a></li>
            <li class="list-inline-item"><a href="./faq.html" class="link-secondary">FAQ</a></li>
        </ul>
        </div>
        <div class="col-12 col-lg-auto mt-3 mt-lg-0">
        Copyright © 2020, Rentsy is built by passionate people in Toronto.
        </div>
    </div>
    </div>
</footer>

lib/rentsy_web/templates/layout/partials/_header.html.eex
<header class="navbar navbar-expand-md navbar-light">
    <div class="container-xl">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a href="<%= Routes.page_url(@conn, :index) %>" class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pr-0 pr-md-3">
            <img src="/images/logo.png" alt="Tabler" class="navbar-brand-image">
        </a>
        <div class="collapse navbar-collapse" id="navbar-menu">
            <div class="d-flex flex-column flex-md-row flex-fill align-items-stretch align-items-md-center">
                <%= if is_public_page?(@conn) do %>
                    <%= render "partials/_public_nav.html", conn: @conn %>
                <% else %>
                <ul class="navbar-nav">
                    <%= render "partials/_private_nav.html", conn: @conn %>
                </ul>
                <% end %>
            </div>
        </div>
        <%= render "partials/_user_dropdown.html", conn: @conn %>
    </div>
</header>

lib/rentsy_web/templates/layout/partials/_private_nav.html.eex
<ul class="navbar-nav">
    <li class="nav-item">
    </li>
    <%= if is_landlord?(@conn) do %>
        <div class="nav-item dropdown">
            <a href="#" class="nav-link" data-toggle="dropdown">Search</a>
            <div class="dropdown-menu dropdown-menu-left">
                <%# <%= link "Search Experts", to: Routes.search_expert_path(@conn, :index), class: "dropdown-item" %> %>
                <%# <%= link "Search Projects", to: Routes.search_project_path(@conn, :index), class: "dropdown-item" %> %>
            </div>
        </div>
    <% else %>
        <li class="nav-item">
        </li>
        <li class="nav-item">
        </li>
    <% end %>
</ul>

lib/rentsy_web/templates/layout/partials/_public_nav.html.eex
<ul class="navbar-nav">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" >
            <span class="nav-link-title">
                Solutions
            </span>
        </a>
        <ul class="dropdown-menu">
            <li >
                <a class="dropdown-item" href="./invoice.html" >
                Platform Overview
                </a>
            </li>
            <li >
                <a class="dropdown-item" href="./blog.html" >
                Expert Marketplace
                </a>
            </li>
        </ul>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link" href="./#" >
            <span class="nav-link-title">
                Pricing
            </span>
        </a>
    </li>
</ul>

lib/rentsy_web/templates/layout/partials/_user_dropdown.html.eex
 <%= if @conn.assigns.current_user do %>
    <%= if is_public_page?(@conn) do %>
        <div class="navbar-nav flex-row order-md-last">
            <li class="nav-item">
                <span class="nav-link-title">
                    <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "btn btn-cyan btn-block" %>
                </span>
            </li>
        </div>
    <% else %>
        <%= render "partials/_dropdown.html", conn: @conn %>
    <% end %>
<% else %>
    <div class="navbar-nav order-md-last">
        <li class="nav-item">
            <span class="nav-link-title">
                <%= link "Sign in / Register", to: Routes.user_session_path(@conn, :new), class: "btn btn-cyan btn-block" %>
            </span>
        </li>
    </div>
<% end %>